### ISSUE TITLE
Source reference in function header to GitHub not working

### ISSUE THREAD

**Issue by kianmeng** [OldhamMade/TeslaCacher#2]
Since this module `source_ref` was set using `v#{@version}`, the function header link to GitHub, https://github.com/OldhamMade/TeslaCacher/blob/v0.3.0/lib/tesla_cacher.ex#L57 is not working right (HTTP 404) now as releases are not tagged.

**Comment by OldhamMade** [comment]
Created tags for all previous versions. Closing, and thanks for raising the issue!

**Comment by OldhamMade** [comment]
Created tags for all previous versions. Closing, and thanks for raising the issue!
